# This is a restricted test set for OpenTofu
# The full test is defined in the test.yml workflow.
# This file is intended to focus testing the OpenTofu compatibility against the latest provider version.
name: OpenTofu Provider Tests

on:
  workflow_dispatch:

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read

env:
  LATEST_VERSION: 1.9.*

jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4 # v4.0.0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: |
         go mod download
         go mod tidy
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837 # v3.7.1
        with:
          version: latest
          skip-cache: true


  # Run acceptance tests in a matrix with OpenTofu CLI versions
  test:
    name: Terraform Provider Acceptance Tests for OpenTofu
    needs: build
    runs-on: ubuntu-latest
    # Timeout for tests set to 25 minutes to safeguard long running tests (specifically for service instances)
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        # List of OpenTofu versions to be tested - last three versions are in scope
        # Check https://endoflife.date/opentofu for end of support dates
        # '1.6.*' end of security support 09 Jan 2025
        opentofu:
          - '1.7.*'
          - '1.8.*'
          - '1.9.*'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version-file: 'go.mod'
          cache: false
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.opentofu }}
          tofu_wrapper: false
      - run: |
         go mod download
         go mod tidyy
         - run: go test -v -timeout=1800s -parallel=4 ./...
         if: ${{ matrix.opentofu }} != ${{ env.LATEST_VERSION }}
         env:
           TF_ACC: "1"
         timeout-minutes: 20
       # For the latest version we use a dedicated action for a visual display of the test results
      - uses: robherley/go-test-action@v0
        if: ${{ matrix.opentofu == env.LATEST_VERSION}}
        env:
          TF_ACC: "1"
        with:
          testArguments: -v -timeout=1800s -parallel=4 ./...
