# This is a restricted test set for OpenTofu
# The full test is defined in the test.yml workflow.
# This file is intended to focus testing the OpenTofu compatibility against the latest provider version.
name: OpenTofu Provider Tests

on:
  workflow_dispatch:

# Testing only needs permissions to read the repository contents.
permissions:
  contents: read


jobs:
  # Ensure project builds before running testing matrix
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4 # v4.0.0
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: 'go.mod'
          cache: false
      - run: |
         go mod download
         go mod tidy
      - run: go build -v .
      - name: Run linters
        uses: golangci/golangci-lint-action@2226d7cb06a077cd73e56eedd38eecad18e5d837 # v3.7.1
        with:
          version: latest
          skip-cache: true


  # Run acceptance tests in a matrix with OpenTofu CLI versions
  test:
    name: Terraform Provider Acceptance Tests for OpenTofu
    needs: build
    runs-on: ubuntu-latest
    # Timeout for tests set to 25 minutes to safeguard long running tests (specifically for service instances)
    timeout-minutes: 25
    strategy:
      fail-fast: false
      matrix:
        # list of OpenTofu versions to test against
        opentofu:
          - '1.6.*'
          - '1.7.*'
          - '1.8.*'
          - '1.9.*'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version-file: 'go.mod'
          cache: false
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: ${{ matrix.opentofu }}
          tofu_wrapper: false
      - run: |
         go mod download
         go mod tidyy
      - env:
          TF_ACC: "1"
        run: go test -v -cover -coverprofile=cover.out -timeout=1800s -parallel=4 ./...
        timeout-minutes: 20
